### ISSUE TITLE
some questions about training error

### ISSUE THREAD

**Issue by immarioo** [vita-epfl/social-nce#9]
hello, thanks for you available code.
i met error like this when i run "python imitate.py --contrast_weight=2.0 --contrast_sampling='local' --gpu" in crowd_nav path, the error information is: 
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
it seems that the attention's linear operation got the wrong shapes, what should i do? 
thanks :)

**Comment by YuejiangLIU** [comment]
Thanks for reporting this. I didn't encounter this error before, but I suppose it is related to the pytorch version or other env settings.

Do you know which line of code causes the error?

p.s., the following pages seem to contain some general info about your reported issue. 
- [link1](https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544)
- [link2](https://github.com/pytorch/pytorch/issues/64097)

**Comment by immarioo** [comment]
thank you, i follow the step mentioned in the link1, and it worked, the problem is the pytorch version is mismatch the cuda version.
